export const constructorOptions = new Map()
.set('alfa_romeo', 'alfa')
.set('alpine_team', 'alphatauri')
.set('alphatauri', 'alpine')
.set('aston_martin', 'aston_martin')
.set('ferrari', 'ferrari')
.set('haas_Team', 'haas')
.set('mclaren', 'mclaren')
.set('red_bull', 'red_bull')
.set('williams', 'williams')
