export const countryToNationality = new Map([
  ['Somali', 'Somalia'],
  ['Liechtensteiner', 'Liechtenstein'],
  ['Moroccan', 'Morocco'],
  ['Sahrawi', 'Western Sahara'],
  ['Serbian', 'Serbia'],
  ['Afghan', 'Afghanistan'],
  ['Angolan', 'Angola'],
  ['Albanian', 'Albania'],
  ['Åland Islander', 'Åland Islands'],
  ['Andorran', 'Andorra'],
  ['Emirati', 'United Arab Emirates'],
  ['Argentine', 'Argentina'],
  ['Armenian', 'Armenia'],
  ['American Samoan', 'American Samoa'],
  ['French', 'France'],
  ['Antiguan, Barbudan', 'Antigua and Barbuda'],
  ['Australian', 'Australia'],
  ['Austrian', 'Austria'],
  ['Azerbaijani', 'Azerbaijan'],
  ['Burundian', 'Burundi'],
  ['Belgian', 'Belgium'],
  ['Beninese', 'Benin'],
  ['Burkinabe', 'Burkina Faso'],
  ['Bangladeshi', 'Bangladesh'],
  ['Bulgarian', 'Bulgaria'],
  ['Bahraini', 'Bahrain'],
  ['Bahamian', 'Bahamas'],
  ['Bosnian, Herzegovinian', 'Bosnia and Herzegovina'],
  ['Belarusian', 'Belarus'],
  ['Belizean', 'Belize'],
  ['Bermudian', 'Bermuda'],
  ['Bolivian', 'Bolivia'],
  ['Brazilian', 'Brazil'],
  ['Barbadian', 'Barbados'],
  ['Bruneian', 'Brunei'],
  ['Bhutanese', 'Bhutan'],
  ['Motswana', 'Botswana'],
  ['Central African', 'Central African Republic'],
  ['Canadian', 'Canada'],
  ['Swiss', 'Switzerland'],
  ['Chilean', 'Chile'],
  ['Chinese', 'China'],
  ['Ivorian', 'Côte d\'Ivoire'],
  ['Cameroonian', 'Cameroon'],
  ['Congolese', 'Democratic Republic of the Congo'],
  ['Colombian', 'Colombia'],
  ['Comorian', 'Comoros'],
  ['Cape Verdean', 'Cape Verde'],
  ['Costa Rican', 'Costa Rica'],
  ['Cuban', 'Cuba'],
  ['Curaçaoan', 'Curaçao'],
  ['Caymanian', 'Cayman Islands'],
  ['Turkish Cypriot', 'Northern Cyprus'],
  ['Cypriot', 'Cyprus'],
  ['Czech', 'Czech Republic'],
  ['German', 'Germany'],
  ['Djiboutian', 'Djibouti'],
  ['Dominican', 'Dominica'],
  ['Danish', 'Denmark'],
  ['Dominican', 'Dominican Republic'],
  ['Algerian', 'Algeria'],
  ['Ecuadorean', 'Ecuador'],
  ['Egyptian', 'Egypt'],
  ['Eritrean', 'Eritrea'],
  ['Spanish', 'Spain'],
  ['Estonian', 'Estonia'],
  ['Ethiopian', 'Ethiopia'],
  ['Finnish', 'Finland'],
  ['Fijian', 'Fiji'],
  ['Falkland Islander', 'Falkland Islands'],
  ['Micronesian', 'Micronesia'],
  ['Faroe Islander', 'Faroe Islands'],
  ['French Guianese', 'French Guiana'],
  ['Gabonese', 'Gabon'],
  ['British', 'United Kingdom'],
  ['Georgian', 'Georgia'],
  ['Guernseyman, Channel Islander', 'Guernsey'],
  ['Ghanaian', 'Ghana'],
  ['Gibraltar', 'Gibraltar'],
  ['Guinean', 'Guinea'],
  ['Guadeloupean', 'Guadeloupe'],
  ['Gambian', 'Gambia'],
  ['Guinean', 'Equatorial Guinea'],
  ['Greek', 'Greece'],
  ['Grenadian', 'Grenada'],
  ['Greenlander', 'Greenland'],
  ['Guatemalan', 'Guatemala'],
  ['French Guianese', 'Guiana'],
  ['Guamanian, Chamorro', 'Guam'],
  ['Guyanese', 'Guyana'],
  ['Hong Konger', 'Hong Kong'],
  ['Honduran', 'Honduras'],
  ['Croatian', 'Croatia'],
['Haitian', 'Haiti'],
['Hungarian', 'Hungary'],
['Indonesian', 'Indonesia'],
['Isle of Man', 'Isle of Man'],
['Indian', 'India'],
['British Indian Ocean Territory', 'British Indian Ocean Territory'],
['Irish', 'Ireland'],
['Iranian', 'Iran'],
['Iraqi', 'Iraq'],
['Icelandic', 'Iceland'],
['Israeli', 'Israel'],
['Italian', 'Italy'],
['Jamaican', 'Jamaica'],
['Jerseyman, Channel Islander', 'Jersey'],
['Jordanian', 'Jordan'],
['Japanese', 'Japan'],
['Kazakhstani', 'Kazakhstan'],
['Kenyan', 'Kenya'],
['Kyrgyzstani', 'Kyrgyzstan'],
['Cambodian', 'Cambodia'],
['Kiribatian', 'Kiribati'],
['Saint Kitts and Nevis', 'Kittitian and Nevisian'],
['South Korean', 'South Korea'],
['Kosovar', 'Kosovo'],
['Kuwaiti', 'Kuwait'],
['Kosovan', 'Kosovo'],
['Laotian', 'Laos'],
['Lebanese', 'Lebanon'],
['Liberian', 'Liberia'],
['Libyan', 'Libya'],
['Saint Lucian', 'Saint Lucian'],
['Liechtensteiner', 'Liechtenstein'],
['Sri Lankan', 'Sri Lankan'],
['Basotho', 'Lesotho'],
['Lithuanian', 'Lithuania'],
['Luxembourger', 'Luxembourgish'],
['Latvian', 'Latvia'],
['Macanese', 'Macau'],
['Moroccan', 'Moroccan'],
['Monegasque', 'Monegasque'],
['Moldovan', 'Moldova'],
['Malagasy', 'Malagasy'],
['Maldivian', 'Maldivian'],
['Mexican', 'Mexican'],
['Marshallese', 'Marshallese'],
['Macedonian', 'Macedonian'],
['Malian', 'Mali'],
['Maltese', 'Malta'],
['Burmese', 'Burmese'],
['Montenegrin', 'Montenegrin'],
['Mongolian', 'Mongolia'],
['Northern Mariana Islander', 'Northern Marianan'],
['Mozambican', 'Mozambican'],
['Mauritanian', 'Mauritanian'],
['Mauritian', 'Mauritian'],
['Mahoran, Mahorais', 'Mahoran, Mahorais'],
['Namibian', 'Namibian'],
['New Caledonian', 'New Caledonian'],
['Nigerien', 'Nigerien'],
['Norfolk Islander', 'Norfolk Islander'],
['Nigerian', 'Nigerian'],
['Nicaraguan', 'Nicaraguan'],
['Niuean', 'Niuean'],
['Dutch', 'Dutch'],
['Norwegian', 'Norwegian'],
['Nepalese', 'Nepali'],
['Nauruan', 'Nauruan'],
['New Zealander', 'New Zealander'],
['Omani', 'Omani'],
['Pakistani', 'Pakistani'],
['Panamanian', 'Panamanian'],
['Pitcairn Islander', 'Pitcairn Islander'],
['Peruvian', 'Peruvian'],
['Filipino', 'Filipino'],
['Palauan', 'Palauan'],
['Papua New Guinean', 'Papua New Guinean'],
['Polish', 'Polish'],
['Puerto Rican', 'Puerto Rican'],
['North Korean', 'North Korean'],
['Portuguese', 'Portuguese'],
['Paraguayan', 'Paraguayan'],
['Palestinian', 'Palestinian'],
['Qatari', 'Qatari'],
['Réunionese, Réunionnais', 'Réunionese, Réunionnais'],
['Romanian', 'Romanian'],
['Russian', 'Russian'],
['Rwandan', 'Rwandan'],
['Saudi Arabian', 'Saudi Arabian'],
['Sudanese', 'Sudanese'],
['Senegalese', 'Senegalese'],
['Singaporean', 'Singaporean'],
['South Georgia and the South Sandwich Islander', 'South Georgia and South Sandwich Islands'],
['Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian'],
['Slovak', 'Slovak'],
['Sierra Leonean', 'Sierra Leonean'],
['Slovenian', 'Slovenian'],
['Somali', 'Somalian'],
['Swazi', 'Swazi'],
['Sint Maarten', 'Sint Maartener'],
['Seychellois', 'Seychellois'],
['Syrian', 'Syrian'],
['Turks and Caicos Islander', 'Turks and Caicos Islander'],
['Chadian', 'Chadian'],
['Togolese', 'Togolese'],
['Thai', 'Thai'],
['Tajikistani', 'Tajikistani'],
['Tokelauan', 'Tokelauan'],
['Turkmen', 'Turkmen'],
['Timorese', 'Timorese'],
['Tongan', 'Tongan'],
['Trinidadian, Tobagonian', 'Trinidadian and Tobagonian'],
['Tunisian', 'Tunisian'],
['Turkish', 'Turkish'],
['Tuvaluan', 'Tuvaluan'],
['Taiwanese', 'Taiwanese'],
['Tanzanian', 'Tanzanian'],
['Ugandan', 'Ugandan'],
['Ukrainian', 'Ukrainian'],
['Uruguayan', 'Uruguayan'],
['Uzbek', 'Uzbek'],
['Vatican', 'Vatican City'],
['Vincentian', 'Saint Vincent and the Grenadines'],
['Venezuelan', 'Venezuelan'],
['Virgin Islander', 'British Virgin Islands'],
['Vietnamese', 'Vietnamese'],
['Ni-Vanuatu', 'Vanuatu'],
['Wallis and Futuna Islander', 'Wallis and Futuna'],
['Sammarinese', 'San Marino'],
['Sao Tomean, Santomean', 'São Tomé and Príncipe'],
['Yemeni', 'Yemen'],
['South African', 'South African'],
['Zambian', 'Zambian'],
['Zimbabwean', 'Zimbabwe'],
['Swedish', 'Sweden'],
['American', 'united States'],
[]
])
